<a href="https://colab.research.google.com/github/inventwithdean/transformers/blob/main/EnterPositionalEncodings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
torch.manual_seed(1337)
Keys = torch.randn((6, 6))
Queries = torch.randn((6, 6))
Values = torch.randn((6, 6))
EmbeddingMat = torch.randn((3, 6))
a = torch.tensor(([0, 1, 2]))

In [ ]:
a = EmbeddingMat[a] # Embeddings of three random words
a


tensor([[ 1.6218,  1.0775,  0.4941,  0.4672, -0.3454, -1.1625],
        [ 0.1445,  0.1663,  0.7507,  0.9132, -1.4355, -1.5304],
        [ 0.9593,  1.0600,  0.6299, -1.2867, -0.6875,  2.1382]])

In [ ]:
k = a @ Keys
q = a @ Queries
v = a @ Values
attention = q @ k.T / torch.sqrt(torch.tensor(6))
attention = torch.softmax(attention, dim=-1) @ v
attention

tensor([[-1.3528, -0.1137,  2.1152, -0.6947, -1.3591, -3.5024],
        [-1.8490, -0.4083, -3.4174, -0.1400,  3.5685, -0.7615],
        [-1.3947, -0.1427,  2.1633, -0.7062, -1.3753, -3.5444]])

In [ ]:
a = torch.tensor([1, 0, 2])
a = EmbeddingMat[a]
a

tensor([[ 0.1445,  0.1663,  0.7507,  0.9132, -1.4355, -1.5304],
        [ 1.6218,  1.0775,  0.4941,  0.4672, -0.3454, -1.1625],
        [ 0.9593,  1.0600,  0.6299, -1.2867, -0.6875,  2.1382]])

In [ ]:
k = a @ Keys
q = a @ Queries
v = a @ Values
attention = q @ k.T / torch.sqrt(torch.tensor(6))
attention = torch.softmax(attention, dim=-1) @ v
attention

tensor([[-1.8490, -0.4083, -3.4174, -0.1400,  3.5685, -0.7615],
        [-1.3528, -0.1137,  2.1152, -0.6947, -1.3591, -3.5024],
        [-1.3947, -0.1427,  2.1633, -0.7062, -1.3753, -3.5444]])

In [ ]:
# Positional Encodings Enter the Chat
pos_embs = torch.randn((3, 6))

In [ ]:

a = torch.tensor([0, 1, 2])
a = EmbeddingMat[a] # Embeddings of three random words with positional encodings
print(a)
a = a + pos_embs
print(a)

tensor([[ 1.6218,  1.0775,  0.4941,  0.4672, -0.3454, -1.1625],
        [ 0.1445,  0.1663,  0.7507,  0.9132, -1.4355, -1.5304],
        [ 0.9593,  1.0600,  0.6299, -1.2867, -0.6875,  2.1382]])
tensor([[ 2.4991,  1.3619,  0.7925, -0.2592, -0.6573, -1.6185],
        [ 0.7886,  0.7736,  1.9904,  1.6457, -0.9313, -0.6591],
        [ 0.6852,  0.3131,  0.0466, -0.9168, -1.2431,  1.7399]])


In [ ]:
k = a @ Keys
q = a @ Queries
v = a @ Values
attention = q @ k.T / torch.sqrt(torch.tensor(6))
attention = torch.softmax(attention, dim=-1) @ v
attention

tensor([[ 0.9350,  1.7850, -2.0714, -1.2383,  0.5619, -1.7110],
        [-1.8599, -0.1087, -1.2315, -0.3081,  1.6290, -2.2386],
        [-3.7722, -1.2333, -0.4730,  0.6816,  2.2535, -2.2433]])

In [ ]:
a = torch.tensor([1, 0, 2])
a = EmbeddingMat[a]
print(a)
a = a + pos_embs
print(a)

tensor([[ 0.1445,  0.1663,  0.7507,  0.9132, -1.4355, -1.5304],
        [ 1.6218,  1.0775,  0.4941,  0.4672, -0.3454, -1.1625],
        [ 0.9593,  1.0600,  0.6299, -1.2867, -0.6875,  2.1382]])
tensor([[ 1.0217,  0.4508,  1.0491,  0.1868, -1.7474, -1.9864],
        [ 2.2659,  1.6848,  1.7337,  1.1997,  0.1588, -0.2912],
        [ 0.6852,  0.3131,  0.0466, -0.9168, -1.2431,  1.7399]])


In [ ]:
k = a @ Keys
q = a @ Queries
v = a @ Values
attention = q @ k.T / torch.sqrt(torch.tensor(6))
attention = torch.softmax(attention, dim=-1) @ v
attention

tensor([[-3.7611, -1.2244, -0.4642,  0.6738,  2.2389, -2.2478],
        [-1.0821,  1.1014,  1.9703, -0.9633, -1.5244, -3.1133],
        [-3.5851, -1.0705, -0.2974,  0.5648,  1.9858, -2.3074]])

In [ ]:
# You can see how attention of last token is different with different orders of previous words!
#  That's what we need 🙂
# We don't want "Dean is hunting ghost" and "Ghost is hunting dean" to be same
# in transformer's eyes so to speak 😄